In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import IPython.display as ipd
import librosa
import librosa.display
import os
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [173]:
import pyaudio
import wave


chunk = 1024  # Record in chunks of 1024 samples
sample_format = pyaudio.paInt16  # 16 bits per sample
channels = 2
fs = 44100  # Record at 44100 samples per second
seconds = 5
filename = "output.wav"

p = pyaudio.PyAudio()  # Create an interface to PortAudio

print('Recording')

stream = p.open(format=sample_format,
                channels=channels,
                rate=fs,
                frames_per_buffer=chunk,
                input=True)

frames = []  # Initialize array to store frames

# Store data in chunks for 3 seconds
for i in range(0, int(fs / chunk * seconds)):
    data = stream.read(chunk)
    frames.append(data)

# Stop and close the stream 
stream.stop_stream()
stream.close()
# Terminate the PortAudio interface
p.terminate()

print('Finished recording')
""
# Save the recorded data as a WAV file
wf = wave.open(filename, 'wb')
wf.setnchannels(channels)
wf.setsampwidth(p.get_sample_size(sample_format))
wf.setframerate(fs)
wf.writeframes(b''.join(frames))
wf.close()

Recording
Finished recording


In [16]:
path1='C:/Users/Lenovo/surprised.wav'
path2='C:/Users/Lenovo/sad.wav'
path3='C:/Users/Lenovo/angry.wav'
path4='C:/Users/Lenovo/happy.wav'
ipd.Audio(path4)

In [6]:
voice_1,sr=librosa.load(path1)
voice_2,sr=librosa.load(path2)
voice_3,sr=librosa.load(path3)
voice_4,sr=librosa.load(path4)
print(voice_1.shape)

(110080,)


In [7]:
mlp_model=keras.models.load_model('C:/Sem-4/BCS_summer_project_SER/mlp_model/mlp_model_Team-4/')

In [8]:
def extract_feature_mlp(file):
    result=np.array([])
    mfcc = np.mean(librosa.feature.mfcc(file,sr=sr,n_mfcc=40).T,axis=0)
    result = np.hstack((result,mfcc))
    chroma=np.mean(librosa.feature.chroma_stft(file,sr=sr).T,axis=0)
    result=np.hstack((result,chroma))
    mel = np.mean(librosa.feature.melspectrogram(file,sr=sr).T,axis=0)
    result = np.hstack((result,mel))
    spectral_rolloff = np.mean(librosa.feature.spectral_rolloff(file, sr=sr).T,axis=0)
    result = np.hstack((result,spectral_rolloff))

    return result

In [9]:
x=[]
feature=extract_feature_mlp(voice_1)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(mlp_model.predict(x))
x=[]
feature=extract_feature_mlp(voice_2)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(mlp_model.predict(x))
x=[]
feature=extract_feature_mlp(voice_3)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(mlp_model.predict(x))
x=[]
feature=extract_feature_mlp(voice_4)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(mlp_model.predict(x))

[[0. 1. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0. 0. 0. 0.]]


In [10]:
cnn_model=keras.models.load_model('C:/Sem-4/BCS_summer_project_SER/cnn_model/cnn_model_team-4/')

In [11]:
def extract_feature_cnn(file):
    result=np.array([])
    mfcc = np.mean(librosa.feature.mfcc(file,sr=sr,n_mfcc=20).T,axis=0)
    result = np.hstack((result,mfcc))
    spec_centroid = np.mean(librosa.feature.spectral_centroid(file,sr).T,axis=0)
    result = np.hstack((result,spec_centroid))
    spec_bandwidth = np.mean(librosa.feature.spectral_bandwidth(file,sr).T,axis=0)
    result = np.hstack((result,spec_bandwidth))
    spec_contrast = np.mean(librosa.feature.spectral_contrast(file,sr).T,axis=0)
    result=np.hstack((result,spec_contrast))
    spec_flat = np.mean(librosa.feature.spectral_flatness(file).T,axis=0)
    result=np.hstack((result,spec_flat))

    return result

In [12]:
x=[]
feature=extract_feature_cnn(voice_1)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(cnn_model.predict(x))
x=[]
feature=extract_feature_cnn(voice_2)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(cnn_model.predict(x))
x=[]
feature=extract_feature_cnn(voice_3)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(cnn_model.predict(x))
x=[]
feature=extract_feature_cnn(voice_4)
x.append(feature)
x=np.array(x)
x=np.expand_dims(x,axis=2)
print(cnn_model.predict(x))

[[0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0.]]


array([[0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)